-- MySQL Script generated by MySQL Workbench
-- Thu 21 Oct 2021 07:31:21 PM +05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genres` (
  `idGenres` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idGenres`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PublishingHome`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PublishingHome` (
  `idPublishingHome` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPublishingHome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Books` (
  `idBooks` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `God_izdaniya` VARCHAR(4) NOT NULL,
  `Genres_idGenres` INT NOT NULL,
  `PublishingHome_idPublishingHome` INT NOT NULL,
  PRIMARY KEY (`idBooks`),
  INDEX `fk_Books_Genres1_idx` (`Genres_idGenres` ASC) VISIBLE,
  INDEX `fk_Books_PublishingHome1_idx` (`PublishingHome_idPublishingHome` ASC) VISIBLE,
  CONSTRAINT `fk_Books_Genres1`
    FOREIGN KEY (`Genres_idGenres`)
    REFERENCES `mydb`.`Genres` (`idGenres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Books_PublishingHome1`
    FOREIGN KEY (`PublishingHome_idPublishingHome`)
    REFERENCES `mydb`.`PublishingHome` (`idPublishingHome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Authors` (
  `idAuthorsOfBooks` INT NOT NULL AUTO_INCREMENT,
  `FullName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idAuthorsOfBooks`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AuthorsOfBooks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AuthorsOfBooks` (
  `idAuthorsOfBooks` INT NOT NULL AUTO_INCREMENT,
  `Books_idBooks` INT NOT NULL,
  `Authors_idAuthorsOfBooks` INT NOT NULL,
  PRIMARY KEY (`idAuthorsOfBooks`),
  INDEX `fk_AuthorsOfBooks_Books1_idx` (`Books_idBooks` ASC) VISIBLE,
  INDEX `fk_AuthorsOfBooks_Authors1_idx` (`Authors_idAuthorsOfBooks` ASC) VISIBLE,
  CONSTRAINT `fk_AuthorsOfBooks_Books1`
    FOREIGN KEY (`Books_idBooks`)
    REFERENCES `mydb`.`Books` (`idBooks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AuthorsOfBooks_Authors1`
    FOREIGN KEY (`Authors_idAuthorsOfBooks`)
    REFERENCES `mydb`.`Authors` (`idAuthorsOfBooks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Readers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Readers` (
  `idReaders` INT NOT NULL AUTO_INCREMENT,
  `FullName` VARCHAR(100) NOT NULL,
  `Passport` VARCHAR(12) NOT NULL,
  `DOB` DATE NOT NULL,
  `Street` VARCHAR(45) NOT NULL,
  `Home` VARCHAR(3) NOT NULL,
  `ApartmentNumber` VARCHAR(4) NOT NULL,
  `PhoneNumber` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idReaders`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Provider` (
  `idProvider` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProvider`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Instance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Instance` (
  `idInstance` INT NOT NULL AUTO_INCREMENT,
  `DateOfReceipt` DATE NOT NULL,
  `Provider_idProvider` INT NOT NULL,
  `Books_idBooks` INT NOT NULL,
  PRIMARY KEY (`idInstance`),
  INDEX `fk_Instance_Provider1_idx` (`Provider_idProvider` ASC) VISIBLE,
  INDEX `fk_Instance_Books1_idx` (`Books_idBooks` ASC) VISIBLE,
  CONSTRAINT `fk_Instance_Provider1`
    FOREIGN KEY (`Provider_idProvider`)
    REFERENCES `mydb`.`Provider` (`idProvider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Instance_Books1`
    FOREIGN KEY (`Books_idBooks`)
    REFERENCES `mydb`.`Books` (`idBooks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ReaderTicket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ReaderTicket` (
  `idReaderTicket` INT NOT NULL AUTO_INCREMENT,
  `DateOfIssue` DATE NOT NULL,
  `ExtensionPeriod` DATE NOT NULL,
  `ReturnOfBooks` VARCHAR(45) NOT NULL,
  `Readers_idReaders` INT NOT NULL,
  `Instance_idInstance` INT NOT NULL,
  PRIMARY KEY (`idReaderTicket`),
  INDEX `fk_ReaderTicket_Readers1_idx` (`Readers_idReaders` ASC) VISIBLE,
  INDEX `fk_ReaderTicket_Instance1_idx` (`Instance_idInstance` ASC) VISIBLE,
  CONSTRAINT `fk_ReaderTicket_Readers1`
    FOREIGN KEY (`Readers_idReaders`)
    REFERENCES `mydb`.`Readers` (`idReaders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ReaderTicket_Instance1`
    FOREIGN KEY (`Instance_idInstance`)
    REFERENCES `mydb`.`Instance` (`idInstance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
