# Generated by Django 3.2.8 on 2021-10-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('idauthorsofbooks', models.AutoField(db_column='idAuthorsOfBooks', primary_key=True, serialize=False)),
                ('fullname', models.CharField(db_column='FullName', max_length=100)),
            ],
            options={
                'db_table': 'Authors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Authorsofbooks',
            fields=[
                ('idauthorsofbooks', models.AutoField(db_column='idAuthorsOfBooks', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'AuthorsOfBooks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('idbooks', models.AutoField(db_column='idBooks', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('god_izdaniya', models.IntegerField(db_column='God_izdaniya')),
            ],
            options={
                'db_table': 'Books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('idgenres', models.AutoField(db_column='idGenres', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'Genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('idinstance', models.AutoField(db_column='idInstance', primary_key=True, serialize=False)),
                ('dateofreceipt', models.DateField(db_column='DateOfReceipt')),
            ],
            options={
                'db_table': 'Instance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('idprovider', models.IntegerField(db_column='idProvider', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45)),
            ],
            options={
                'db_table': 'Provider',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publishinghome',
            fields=[
                ('idpublishinghome', models.AutoField(db_column='idPublishingHome', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45)),
            ],
            options={
                'db_table': 'PublishingHome',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Readers',
            fields=[
                ('idreaders', models.AutoField(db_column='idReaders', primary_key=True, serialize=False)),
                ('fullname', models.CharField(db_column='FullName', max_length=100)),
                ('passport', models.IntegerField(db_column='Passport')),
                ('dob', models.DateField(db_column='DOB')),
                ('street', models.CharField(db_column='Street', max_length=45)),
                ('home', models.IntegerField(db_column='Home')),
                ('apartmentnumber', models.IntegerField(db_column='ApartmentNumber')),
                ('phonenumber', models.IntegerField(db_column='PhoneNumber')),
            ],
            options={
                'db_table': 'Readers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Readerticket',
            fields=[
                ('idreaderticket', models.AutoField(db_column='idReaderTicket', primary_key=True, serialize=False)),
                ('dateofissue', models.DateField(db_column='DateOfIssue')),
                ('extensionperiod', models.DateField(db_column='ExtensionPeriod')),
                ('returnofbooks', models.CharField(db_column='ReturnOfBooks', max_length=45)),
            ],
            options={
                'db_table': 'ReaderTicket',
                'managed': False,
            },
        ),
    ]
